services:
  - docker

before_install:
  - docker pull asciidoctor/docker-asciidoctor

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN
  on:
    branch: master

script:
  - docker run --rm -v $(pwd):/documents/ asciidoctor/docker-asciidoctor asciidoctor --destination-dir=docs \*.adoc
